name: pcc-no-v1-ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install poppler
        run: sudo apt-get update && sudo apt-get install -y poppler-utils
      - name: Python deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt || true
      - name: Run CI harness
        run: |
          source .venv/bin/activate
          ./scripts/check_poppler.sh
          bash scripts/ci_run.sh
